version: "3.8"

services:
  backend:
    image: kanucast/xyz-backend:latest # am using image from Docker Hub
    container_name: xyz-backend
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - mynetwork

  db:
    image: postgres:15-alpine
    container_name: xyz_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
